language: bash
sudo: false
cache: apt

before_install:
  - openssl aes-256-cbc -K $encrypted_63c9d3fcdbeb_key -iv $encrypted_63c9d3fcdbeb_iv -in gh_rsa.enc -out gh_rsa -d

script:
  - make OUTDIR=../capitalism/

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then
      (
        echo "Update webpage for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log $TRAVIS_COMMIT_RANGE --pretty=oneline;
      ) > $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG;
      mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa;
      git clone -b master git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_BUILD_DIR-master;
      pushd $TRAVIS_BUILD_DIR-master/;
      rm -rf capitalism/;
      mv ../capitalism/ .;
      git config --global user.email "nabijaczleweli@gmail.com";
      git config --global user.name "Nabijaczleweli Autouploader Bot";
      git config --global push.default simple;
      git add .;
      git commit -F ../DOC_UPDATE_MSG;
      git push;
      popd;
    fi
