language: node_js
node_js:
  - 12
sudo: false
dist: xenial
cache:
  directories:
    - /tmp/calibre-installer-cache
    - $HOME/.rustup
    - $HOME/.cargo
    - build
#    From last working build https://travis-ci.org/nabijaczleweli/nabijaczleweli.github.io/builds/583594518#L213
env: CALIBRE_VERSION=3.47.1

before_install:
  - openssl aes-256-cbc -K $encrypted_63c9d3fcdbeb_key -iv $encrypted_63c9d3fcdbeb_iv -in gh_rsa.enc -out gh_rsa -d

install:
  - export PATH="$HOME/calibre:$HOME/.cargo/bin:$PATH"
  -
  - mkdir -p /tmp/calibre-installer-cache && pushd /tmp/calibre-installer-cache
  - wget --no-check-certificate -nc "https://download.calibre-ebook.com/$CALIBRE_VERSION/calibre-$CALIBRE_VERSION-x86_64.txz"
  - popd
  - mkdir -p "$HOME/calibre" && pushd "$HOME/calibre"
  - tar -xaf "/tmp/calibre-installer-cache/calibre-$CALIBRE_VERSION-x86_64.txz"
  - popd
  -
  - ebook-convert --version
  -
  - mkdir -p "$HOME/bin"
  - curl https://sh.rustup.rs | bash -s -- -y --no-modify-path
  - cargo install gen-epub-book || true

script:
  - make OUTDIR=../content/ GEN_EPUB_BOOK="sleep 10; gen-epub-book" ||
    (sleep 1m; make OUTDIR=../content/ GEN_EPUB_BOOK="sleep 10; gen-epub-book") ||
    (sleep 1m; make OUTDIR=../content/ GEN_EPUB_BOOK="sleep 10; gen-epub-book")

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then
      (
        echo "Update webpage for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log $TRAVIS_COMMIT_RANGE --pretty=oneline;
      ) > $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG;
      mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa;
      git clone -b master git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_BUILD_DIR-master;
      pushd $TRAVIS_BUILD_DIR-master/;
      rm -rf content/;
      mv ../content/ .;
      git config --global user.email "nabijaczleweli@gmail.com";
      git config --global user.name "Nabijaczleweli Autouploader Bot";
      git config --global push.default simple;
      git add -A .;
      git commit -F ../DOC_UPDATE_MSG --date="$(git log "$TRAVIS_COMMIT_RANGE" -1 --pretty="%ai" || date -Iseconds)";
      git push;
      popd;
    fi
