language: node_js
node_js:
  - 7
sudo: false
dist: precise
cache:
  directories:
    - /tmp/calibre-installer-cache
    - build

before_install:
  - openssl aes-256-cbc -K $encrypted_63c9d3fcdbeb_key -iv $encrypted_63c9d3fcdbeb_iv -in gh_rsa.enc -out gh_rsa -d

install:
  - export PATH="$HOME/calibre:$HOME/bin:$PATH"
  - curl -SL https://download.calibre-ebook.com/linux-installer.py | python -c "import sys; import os; main=lambda x:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main(os.getenv('HOME'))"
  - ebook-convert --version
  - mkdir "$HOME/bin"
  - GEN_EPUB_BOOK_RS_VERSION="$(curl -SL https://github.com/nabijaczleweli/gen-epub-book.rs/releases | awk '/h1.*release-title/,/\/h1/' | grep '<a' | awk -F/ '{print($6)}' | awk '-F"' '{print($1); exit}')"
  - echo "$GEN_EPUB_BOOK_RS_VERSION"
  - curl -SL "https://github.com/nabijaczleweli/gen-epub-book.rs/releases/download/$GEN_EPUB_BOOK_RS_VERSION/gen-epub-book.rs-$GEN_EPUB_BOOK_RS_VERSION" -o "$HOME/bin/gen-epub-book"
  - chmod +x "$HOME/bin/gen-epub-book"

script:
  - make OUTDIR=../content/

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then
      (
        echo "Update webpage for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log $TRAVIS_COMMIT_RANGE --pretty=oneline;
      ) > $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG;
      mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa;
      git clone -b master git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_BUILD_DIR-master;
      pushd $TRAVIS_BUILD_DIR-master/;
      rm -rf content/;
      mv ../content/ .;
      git config --global user.email "nabijaczleweli@gmail.com";
      git config --global user.name "Nabijaczleweli Autouploader Bot";
      git config --global push.default simple;
      git add -A .;
      git commit -F ../DOC_UPDATE_MSG;
      git push;
      popd;
    fi
