<!--
nabijaczleweli.xyz (c) by nabijaczleweli@gmail.com (nabijaczleweli)
​
nabijaczleweli.xyz is licensed under a
Creative Commons Attribution 4.0 International License.
​
You should have received a copy of the license along with this
work. If not, see <https://creativecommons.org/licenses/by/4.0/>.
-->


#include "../fontawesome.h"
#include "../common.h"


#define STYLESHEETS FONTAWESOME_LINK                                                                  FORCED_NEWLINE \
                    <link href="/kaschism/assets/column.css" rel="stylesheet" />                      FORCED_NEWLINE \
                    <link href="../writing/Roboto-font.css" rel="stylesheet" />                       FORCED_NEWLINE \
                    <link href="../writing/the_taste_of_mi/Merriweather-font.css" rel="stylesheet" /> FORCED_NEWLINE \
                    <link href="/content/assets/image-header.css" rel="stylesheet" />
BOILERPLATE(Mathematics, Various mathematics-based things, en-GB, STYLESHEETS)


<style>
#include "../writing/the_taste_of_mi/spacing.css"
#include "../indent.css"
</style>


<span class="roboto">
<h2 class="merriweather">(Pretty?) Maths-based things</h2>

<p class="indented continued">
Programming (my drug of choice) is, mainly, applied mathematics (even if just that weird part that nobody likes because it never works),
	and as such it is but natural to apply it to something more fun, like generating a visual medium.
</p>
<p class="indented continuation">
And so these are the visual media generated by combining some bad code and the more abstract (for me, anyway) parts of math,
	including verbal descriptions, algorithms, and, probably more importantly, the pretty stuff.
</p>
</span>


<div>
<p></p>
<a href="mandalas.html"><img src="/content/assets/mandalas/900x900.png" class="header" /></a>
<span class="roboto">
Mandalas generated with Tonči Juričev-Grgin's method.<!--'--><br />
Algorithm, examples, etc. <a href="mandalas.html">inside</a>.<br />
Videos of more complex mandalas over at
  <a href="https://www.youtube.com/watch?v=D2Xk6O9x-yk&list=PL3chI5PWwNA_c1nG57ittUq4op7ZmIveC">YouTube</a></span>
  <a href="https://www.youtube.com/watch?v=D2Xk6O9x-yk&list=PL3chI5PWwNA_c1nG57ittUq4op7ZmIveC">FA(youtube-play)</a>.<br />
<!-- Spacing for header image - is there a way to force the div to accomodate it? -->
<br />
<p></p>
</div>


BOILERPLATE_END()
